version: "3"
services:
  musicbot:
    build: .
    container_name: musicbot
    restart: unless-stopped
    volumes:
      - ./config:/musicbot/config/
      - ./audio_cache:/musicbot/audio_cache
      - ./data:/musicbot/data
      - ./logs:/musicbot/logs
