version: "3"

services:
  app:
    image: nextcloud
    container_name: nextcloud
    restart: always
    volumes:
      - data:/var/www/html
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
    networks:
      - postgres
      - nginx-proxy-manager
    secrets:
      - nextcloud_admin_password
      - nextcloud_admin_user
      - postgres_db
      - postgres_password
      - postgres_user

volumes:
  data:

networks:
  nginx-proxy-manager:
    name: nginx-proxy-network
    external: true
  postgres:
    name: postgres-network
    external: true

secrets:
  nextcloud_admin_password:
    file: ./nextcloud_admin_password.txt
  nextcloud_admin_user:
    file: ./nextcloud_admin_user.txt
  postgres_password:
    file: ../postgres/postgres_password.txt
  postgres_user:
    file: ../postgres/postgres_user.txt

