version: "3"

services:
  agent:
    image: portainer/agent:latest
    container_name: portainer-agent-mbp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    privileged: true
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - 9443:9443
      - 8000:8000
    networks:
      - agent_network
      - nginx-proxy-network

volumes:
  portainer_data:

networks:
  nginx-proxy-network:
    name: nginx-proxy-network
    external: true
  agent_network:
     driver: overlay
     attachable: true
