version: '3'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    privileged: true
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
        - 9000:9000

volumes:
  portainer_data:

networks:
  default:
    name: nginx-proxy-network
    external: true
