version: '3.2'

services:
  agent:
    image: portainer/agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    ports:
      - 9001:9001
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer-ce:latest
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9443:9443"
      - "9000:9000"
      - "8000:8000"
    volumes:
      - portainer_data:/data
    networks:
      - agent_network
      - swarm_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == ubuntu-MacBookPro]

networks:
  agent_network:
    driver: overlay
    attachable: true
  swarm_network:
    external: true

volumes:
  portainer_data:
